name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++ cmake
    
    - name: Compile all C++ files
      run: |
        for file in $(find . -name "*.cpp" -type f); do
          echo "Compiling $file"
          g++ -Wall -Wextra -std=c++17 -o "${file%.cpp}.out" "$file" || echo "Failed to compile $file"
        done
